apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pharma
  name: pharma-ui
  namespace: pharma
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pharma-ui
  template:
    metadata:
      labels:
        app: pharma-ui
    spec:
      containers:
      - name: pharma-ui
      image: docker-registry.dev.datacolab.pt/pharma_j:latest
      ports:
      - containerPort: 80
