apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharma-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pharma-ui
  template:
    metadata:
      labels:
        app: pharma-ui
    spec:
      containers:
      -  image: docker-registry.dev.datacolab.pt/pharma:v3
        name: pharma-ui
        ports:
        - containerPort: 80
