apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharma-v3
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pharma-v3
  template:
    metadata:
        labels:
        app: pharma-v3
    spec:
      containers:
        - image: docker-registry.dev.datacolab.pt/pharma:v3
        name: pharma
        ports:
        - containerPort: 80
