apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharma-deployment
  namespace: pharma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pharma-ui
  template:
    metadata:
      labels:
        app: pharma-ui
    spec:
      containers:
      - name: pharma-ui
        image: docker-registry.dev.datacolab.pt/pharma_j:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registrycredentials
